# Generated by Django 5.2.10 on 2026-02-02 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cypher_query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('average_execution_time', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Query',
                'verbose_name_plural': 'Saved Queries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cypher_query', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('rows_returned', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_executions', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='queries.savedquery')),
            ],
            options={
                'verbose_name': 'Query Execution',
                'verbose_name_plural': 'Query Executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedquery',
            index=models.Index(fields=['created_by'], name='queries_sav_created_9d10c1_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquery',
            index=models.Index(fields=['is_favorite'], name='queries_sav_is_favo_1f2c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='queryexecution',
            index=models.Index(fields=['executed_by', 'executed_at'], name='queries_que_execute_c80ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='queryexecution',
            index=models.Index(fields=['status'], name='queries_que_status_64eb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='queryexecution',
            index=models.Index(fields=['executed_at'], name='queries_que_execute_ea0df7_idx'),
        ),
    ]
